format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/accessom2_restart.nml
  hashes:
    binhash: 7f5d96996712de9815e1db562ad0f039
    md5: 791fd9f9e679f5761ca1763f49088208
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ice/grid.nc
  hashes:
    binhash: 711b136893dbd85c21e62acc5460c83d
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ice/i2o.nc
  hashes:
    binhash: 17de6f79aca30bb1a1b76944d4de3182
    md5: 529e2bb35fc7c7b69cb63a0c3f8d3ffc
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ice/ice.restart_file
  hashes:
    binhash: b4c8b059bd22b8a702eabc460c466546
    md5: 5abe2f39fca319b1c003826e1cb7e81f
work/ice/RESTART/iced.2023-01-01-00000.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ice/iced.2023-01-01-00000.nc
  hashes:
    binhash: a9faff780449d0c60c3b38c0e4fe55bf
    md5: 4f4e9a428152a2184541179d4db4c227
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ice/kmt.nc
  hashes:
    binhash: 15b7b7605699680c3a08d0841aa1bbc5
    md5: 576e78b474c37f61a6fb45c9f5692bc6
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ice/monthly_sstsss.nc
  hashes:
    binhash: 3bef60a79ba7c57443eee3afbeafe76d
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ice/o2i.nc
  hashes:
    binhash: db49f5233d4edcfa4bf2dbab31732bc5
    md5: a47b46f143959f786b3a794fb5692f2f
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ice/sicemass.nc
  hashes:
    binhash: 245dc39e81fc2785b2fc5709a28c18d0
    md5: 795d382b036cf50cc46e825f741eead0
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ice/u_star.nc
  hashes:
    binhash: fa92b91b0fe91910fce3d574762f209f
    md5: 92e5447c707a242a416266a105fe0042
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_age.res.nc
  hashes:
    binhash: 7a88e74edf3beb58e967e77600febd25
    md5: 5eafbfd862a0990611ec088f32f6d6af
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 24bf236251cf9cf573e58286d51c9d45
    md5: 50dacdaa61beac14a00104ac55ebe056
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 12285ee44aee30a7889dd6b358cf39e7
    md5: 4d97a9a1a26477aacdbe47d6231175d9
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_density.res.nc
  hashes:
    binhash: 503afca5b24abee012f93ed596f2fdba
    md5: c2f277424e8164fd6f910faec2f092af
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_frazil.res.nc
  hashes:
    binhash: d63da9e4e203a19ef808d073fe9cf0e8
    md5: 8cb953d31b9541913b6257b6342ad814
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 40bf5f80f46cc601ae9a4ae3278d74f6
    md5: 809751771540e406eaeda69a48cdfcc3
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 2e45a778cb3cb7349f02384376da8f31
    md5: 8dc0eef731829d2234ea65e1b35e1ed7
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 1180fc624280ce4c8990cf73287f0d06
    md5: 40a4924e0f36daf79db196ec3499546c
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_solo.res
  hashes:
    binhash: c2032625ad636dbe4ff7280804690842
    md5: 1025177f6eaa2b3d075d31324fb8bec9
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: cc133306dbc49ad4db1ad7d5634c692b
    md5: bb73b2d0cb82bca3317b1a096c0fb7e3
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1068c9fb93c0186974a075c10a32e5a4
    md5: d444f4a0f8815e44b9fe4b7b84627463
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_tracer.res
  hashes:
    binhash: 78c7d7edd1f33f664be97b12733003d7
    md5: a7699f3cd34d6e6581f41c0403bfefd1
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 9e96386d1f8859e158208c22b2b2e4bd
    md5: ccee9df214e84b01d0c573aa44c687e4
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart369/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 4315732d69ee1d8c270f465e909c44f1
    md5: 60221f41f4388bda6b3fc2117944082d
