format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/accessom2_restart.nml
  hashes:
    binhash: a7052f36c20fcba03bb1b916a0b15d1d
    md5: ddceebaa90e8686733f126015756a52c
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ice/grid.nc
  hashes:
    binhash: fe9754620bd5bdca65d239ae62632a33
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ice/i2o.nc
  hashes:
    binhash: 68b31714dbd871550f83c7bfa2acc8db
    md5: eec2aeac3dba37f14880cc9a140d913b
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ice/ice.restart_file
  hashes:
    binhash: dcb0b97351e42efaf189a1f36f180e59
    md5: 2eaf6c029a4a134923083dcfbd37e378
work/ice/RESTART/iced.2019-01-01-00000.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ice/iced.2019-01-01-00000.nc
  hashes:
    binhash: dfe23375b0fec4400ed50a93a9ea9ab4
    md5: 84474e3ad4a8ed784021dbf0bafda73d
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ice/kmt.nc
  hashes:
    binhash: 03c20e992dca6e8d13b6d6e34723f763
    md5: 576e78b474c37f61a6fb45c9f5692bc6
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ice/monthly_sstsss.nc
  hashes:
    binhash: 5cd8cd6cd47e1403c013f89cbb324d17
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ice/o2i.nc
  hashes:
    binhash: 08503cfc4b7dd20f260d477172f69f4b
    md5: d6f0b9447bb15e1d869da3b428beb576
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ice/sicemass.nc
  hashes:
    binhash: 8cec667ddb84dae91598d9f52f88cf0b
    md5: 059809e0b83bdb6b25a952c0e2298bbe
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ice/u_star.nc
  hashes:
    binhash: 3ba005042b7f5eedb677ff55b1cef885
    md5: c01fc65c434174c740a0590ed543c95a
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_age.res.nc
  hashes:
    binhash: 304704f5041ccf5e976df6fbe345f3a8
    md5: db7e5a48eceda9f6b903dc9233d32cff
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 6dc8c7beaf53e403dcabbb3e4ce56981
    md5: a989883969de993e7531e4230d6c00f2
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3d1eabbe581e1a4afa2784e5178ddd8a
    md5: c8aa9a25bff362ec45d725a19f9a7e03
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_density.res.nc
  hashes:
    binhash: 8409f5a9c07daeda2aa19145545674bb
    md5: 682410b4bce6c2587147758b11aa4f6d
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_frazil.res.nc
  hashes:
    binhash: b07eb44964bb3ddd70cd758e0308a2e3
    md5: b7b581e51b39443647a490cf8d60a660
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 09a79a41d9975bd51c2924022c360b09
    md5: a8ff283a73556c3ec71d5975b875434c
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 1017d9dee878a5041e2822d53ad10a10
    md5: 95e52e4970515823a68420c6be0a0f18
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_sbc.res.nc
  hashes:
    binhash: 89780da80c1b2a3d5da98b226cd73e0b
    md5: 85f694c5e499131eb9772d500527ffa8
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_solo.res
  hashes:
    binhash: 8cba76c1553b1d20fefc8942df2fd564
    md5: a21433ab5717df6e5b9e079ad4b0cd5c
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: f8b30bc76608bc9f92418a12e36b7399
    md5: 939ea03440e84f1ab480d2d6969ec423
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 404844d37f9de4724fe36dc5402ea8a6
    md5: 46f2da25fd6334d09c2f8d29a0a01175
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_tracer.res
  hashes:
    binhash: 5fd91282d9bb0e077a6affe814e83e37
    md5: 63e290a1b31af864d32ed67e8146b07f
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 6ddeb7792f7035004a5e7112a43f74bd
    md5: bc63b3a12ed29324bb24ef88a63c8ed0
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/e14/rmh561/access-om2/archive/025deg_jra55v150_iaf/restart038/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 142722cb586f17be44745857f7a79ce8
    md5: 5d868a1aa7ee519a738137b67e6b4dba
