format: yamanifest
version: 1.0
---
work/accessom2_restart.nml:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/accessom2_restart.nml
  hashes:
    binhash: 8718cce7a7dd42417f12ed3f7d5cddea
    md5: ddceebaa90e8686733f126015756a52c
work/ice/RESTART/grid.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ice/grid.nc
  hashes:
    binhash: 2674b8691c4529627ede193a5a016fcc
    md5: 24920ffb6c0fea5f6ec1e590a5f46280
work/ice/RESTART/i2o.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ice/i2o.nc
  hashes:
    binhash: d8f5c04916063a31c86260afd619a309
    md5: 4b261491f9f082e83b95b68cf2f02a29
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ice/ice.restart_file
  hashes:
    binhash: fb2d963b89ae09456f591e82f9336787
    md5: 2eaf6c029a4a134923083dcfbd37e378
work/ice/RESTART/iced.2019-01-01-00000.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ice/iced.2019-01-01-00000.nc
  hashes:
    binhash: aa7fd3ddfde4a37014df615fd19cb6df
    md5: d65485f1d9af190fbb056708d5111dc2
work/ice/RESTART/kmt.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ice/kmt.nc
  hashes:
    binhash: 68beecbb0a9bd68bc1b4e44122e6e29f
    md5: 576e78b474c37f61a6fb45c9f5692bc6
work/ice/RESTART/monthly_sstsss.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ice/monthly_sstsss.nc
  hashes:
    binhash: e15102b3281cb48ea5164d0573240ca5
    md5: 598c7aa8a08fe3f48a621f781dd26331
work/ice/RESTART/o2i.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ice/o2i.nc
  hashes:
    binhash: c1484ddd9f0a7cfb32ff34729d16766a
    md5: 1ad05f672f757a0d31a67f77363164fc
work/ice/RESTART/sicemass.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ice/sicemass.nc
  hashes:
    binhash: aa3e148bc05fc7f8b249187780387f3b
    md5: b95691346a273c25fc3343d2e0d32a59
work/ice/RESTART/u_star.nc:
  copy: true
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ice/u_star.nc
  hashes:
    binhash: f90c94da4314364db527d6e3fe11c442
    md5: ba611afcf183c0eaf20b8aa673d3da8d
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_age.res.nc
  hashes:
    binhash: 0cabe11ec143cfd68b3b112f0a1cba42
    md5: 7ff94cb011dc71971f8ce0376e557c71
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: 24edf8a4a4c62980963982429eec8f2d
    md5: ea94a219b1eeb8b353a0fd80799438ff
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: b9b416f53a1dd0e3e14edeb8d28afe0c
    md5: 218d6a02d06c5f4d0fc6ea089e4e20d0
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_density.res.nc
  hashes:
    binhash: 115065a81c290d344c64fe604c1be27c
    md5: 8f9435012d32c82e07d7188850a0f9de
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_frazil.res.nc
  hashes:
    binhash: 78b99d850d388a6cce2622fef424eafe
    md5: 289f3cb1af868d16f4831b94e9534930
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 7820e4d301132d84c834f232d5a32d90
    md5: e524c9964cf00af5f7c08655e8011c45
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 7ec8d419cfe3d569e4cfdd517fdc97c1
    md5: a7fb727dcf7e767a1b3672314c540592
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_sbc.res.nc
  hashes:
    binhash: e33932cb680c74b4de86ddc28d48264d
    md5: c9d05d252ca0aabe64c0423e932d802d
work/ocean/INPUT/ocean_solo.res:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_solo.res
  hashes:
    binhash: dfbc110b22568894d71a0777360a8236
    md5: 5519039a6ef1b21674563d1d6d485b77
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: ea951d571d5718c8a46f4003ee055abd
    md5: 139b0ce34a1ae13133d65993701e12c8
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 1073baa888b1e8e7246a1f41dd895bb8
    md5: 905f36132e04d90a6e696cd829e209b5
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_tracer.res
  hashes:
    binhash: 770d3d6d86d40fde5ae1b11a4fa1fdf7
    md5: 62b5bbec9d5d13fb52d72d1af9205cd3
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 180eba0af76408f4c62cc7c72c8b17a2
    md5: 7ab8237f6c2e9ff9ce4acda1b8c6a25f
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /scratch/v45/rmh561/access-om2/archive/025deg_jra55_iaf/restart365/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 7da3f207c5d0d312898880dbc60195f2
    md5: afda8062396df65fbdca7b868a4f44b5
